theme: jekyll-theme-midnight
title: MetaGen
description: Uwutopian friendly ambitious VR nerds
github_url: https://github.com/MetaGenAI/
exclude: ['node_modules']
gems:
  - jekyll-font-awesome-sass
sass:
    sass_dir: assets/css
font-awesome:
  assets: true
